# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: hwsc-dev-container-vars

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: hwscdevcontainer_pw.txt
- script: |
    cat $(Agent.TempDirectory)/hwscdevcontainer_pw.txt | docker login -u "$(hwscDevContainerUser)" --password-stdin hwscdevcontainer.azurecr.io
    docker build --no-cache -f Dockerfile -t $(hwscDevDockerId)/$(hwscDevImageName):$(build.buildId) .
  
  displayName: 'Docker build'
  
- script: |
    docker tag $(hwscDevImageName) $(hwscDevDockerId)/$(hwscDevImageName):$(build.buildId)
    docker push $(hwscDevDockerId)/$(hwscDevImageName):$(build.buildId)
  
  displayName: 'Docker Push'
  
