# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pr:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: hwsc-dev-container-vars

steps:
- script: |
    docker build --no-cache -f Dockerfile -t hwsc/$(hwscDevImageName):$(build.buildId) .
  
  displayName: 'Build Docker Image'
  
- script: |
    docker tag $(hwscDevImageName) hwsc/$(hwscDevImageName):$(build.buildId)
    docker push hwsc/$(hwscDevImageName):$(build.buildId)
  
  displayName: 'Push Docker Image'
  
