# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pr:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: hwsc-dev-container-vars

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: hwscdevcontainer_pw.txt
- script: |
    cat $(Agent.TempDirectory)/hwscdevcontainer_pw.txt | docker login -u "$(hwscDevContainerUser)" --password-stdin
    docker build --no-cache -f Dockerfile -t hwsc/$(hwscDevImageNameDocumentSvc):$(build.buildId) .
  
  displayName: 'Build Docker Image'
  
- script: |
    docker tag $(hwscDevImageNameDocumentSvc) hwsc/$(hwscDevImageNameDocumentSvc):$(build.buildId)
    docker push hwsc/$(hwscDevImageNameDocumentSvc):$(build.buildId)
  
  displayName: 'Push Docker Image'
  
